# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Morfie
tagline:          ''
description:      '"Everything should be made as simple as possible, but not simpler." - Einstein'
url:              http://morfie.fsr.hu

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/morfie
